import type { FastifyServerOptions } from 'fastify'

export const loggerOptions = {
  level: 'info',
  redact: {
    paths: [
      'req.headers.authorization',
      'req.headers.x-api-key',
      'body',
      'req.body',
      'apiKey',
      '*.apiKey',
      'authorization',
      '*.authorization',
      'response',
      '*.response',
      'rawResponse',
      '*.rawResponse',
      'prompt',
      '*.prompt',
      'inputText',
      '*.inputText',
      'output',
      '*.output',
      'images',
      '*.images',
      'manifest',
      '*.manifest',
      'baseUrl',
      '*.baseUrl',
      'originalOutput',
      '*.originalOutput',
      'filename',
      '*.filename',
      'fileName',
      '*.fileName',
      'title',
      '*.title',
      'candidateValue',
      '*.candidateValue',
    ],
    censor: '[Redacted]',
  },
} satisfies NonNullable<FastifyServerOptions['logger']>
