<script setup lang="ts">
import { onMounted, ref } from 'vue'
import FeedbackTemplate from '../components/FeedbackTemplate.vue'
import { detectBrowserCapabilities } from '../browser/browser-capabilities.js'

const releaseId = ref('未生成')
const releaseText = ref('发布编号尚未生成（开发构建）')
const capabilities = detectBrowserCapabilities()

function safeReleaseId(value: unknown): string | null {
  if (typeof value !== 'string' || !/^[A-Za-z0-9._-]{1,80}$/.test(value)) return null
  return value
}

onMounted(async () => {
  try {
    const response = await fetch('/release.json', {
      cache: 'no-store',
      credentials: 'same-origin',
      redirect: 'error',
    })
    if (
      !response.ok ||
      new URL(response.url, window.location.origin).origin !== window.location.origin
    ) return
    const body = (await response.json()) as { releaseId?: unknown }
    const parsed = safeReleaseId(body.releaseId)
    if (parsed !== null) {
      releaseId.value = parsed
      releaseText.value = `发布编号：${parsed}`
    }
  } catch {
    // The release descriptor is generated by the production release task.
  }
})
</script>

<template>
  <main class="about-shell">
    <a href="/">返回首页</a>
    <h1>关于有据</h1>
    <p>有据帮助普通用户整理网购退款纠纷中的材料、事实、时间线和陈述。</p>

    <section>
      <h2>产品边界</h2>
      <p>有据不提供法律咨询、责任结论、赔偿计算、结果预测或自动投诉。AI 是可选增强，默认关闭；用户需自带 API Key，没有共享 Key。</p>
    </section>

    <section>
      <h2>版本与验证状态</h2>
      <p data-release-id>{{ releaseText }}</p>
      <h3>浏览器能力检测</h3>
      <ul>
        <li>IndexedDB：{{ capabilities.indexedDb ? '可用' : '不可用' }}</li>
        <li>OPFS：{{ capabilities.opfs ? '可用' : '不可用' }}</li>
        <li>Web Crypto：{{ capabilities.webCrypto ? '可用' : '不可用' }}</li>
        <li>持久化请求 API：{{ capabilities.storagePersistence ? '可用' : '不可用' }}</li>
      </ul>
      <p class="open-status">真实设备矩阵尚未验证；上述能力检测不等于公开部署的真机验证。</p>
      <p class="open-status">真实 Provider 尚未验证；自动化测试只使用固定响应或 Mock Server。</p>
    </section>

    <FeedbackTemplate :release-id="releaseId" />
  </main>
</template>

<style scoped>
.about-shell { width: min(100%, 48rem); margin: 0 auto; padding: 2rem 1.25rem 5rem; color: #18332c; }
a { color: #31564c; }
h1, h2, h3 { color: #173f35; }
section { margin-top: 1rem; padding: 1rem 1.2rem; border: 1px solid #d3d7ce; border-radius: 0.75rem; background: #fffdf8; line-height: 1.7; }
.open-status { color: #8a4b1d; font-weight: 700; }
</style>
